# Makefile is a script that contains rules
# The rules define how to complile and run your project
# The first rule in the file is the one that is executed when you run "make"
# To run other rules, use their name after make
all:
	g++ main.cpp struct.cpp -o runStructFun
	# ./a.out
	./runStructFun
compile:
	g++ main.cpp struct.cpp -o runStructFun
run:
	./runStructFun